project_id = "zhfzltrxhgdnwzfxnzxl"

[functions.create-checkout]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.check-subscriptions]
verify_jwt = false

[functions.fiscal-webhook]
verify_jwt = false

[functions.focus-nfe-emit]
verify_jwt = false

[functions.focus-nfe-consult]
verify_jwt = false
